


// export const APP_FHIR_API_BASE_URL = "http://hapi.fhir.org/baseR4/";
export const APP_FHIR_API_BASE_URL = "http://localhost:8080/fhir/";

export const QUERY_ORGUNIT_FILTER_KEY = "organization";
export const QUERY_ORGUNIT_FILTER_ID = "202";

export const QUERY_REGISTRATION_FORM_ID = "152";


export const FETCH_LOGIN_REQUEST = "FETCH_LOGIN_REQUEST";
export const FETCH_LOGIN_SUCCESS = "FETCH_LOGIN_SUCCESS";
export const FETCH_LOGIN_FAILURE = "FETCH_LOGIN_FAILURE";


export const FETCH_APP_CONFIG_REQUEST = "FETCH_APP_CONFIG_REQUEST";
export const FETCH_APP_CONFIG_SUCCESS = "FETCH_APP_CONFIG_SUCCESS";
export const FETCH_APP_CONFIG_FAILURE = "FETCH_APP_CONFIG_FAILURE";


export const FETCH_RESOURCE_TYPE_REQUEST = "FETCH_RESOURCE_TYPE_REQUEST";
export const FETCH_RESOURCE_TYPE_SUCCESS = "FETCH_RESOURCE_TYPE_SUCCESS";
export const FETCH_RESOURCE_TYPE_FAILURE = "FETCH_RESOURCE_TYPE_FAILURE";


export const FETCH_RESOURCE_TYPE_DETAILS_REQUEST = "FETCH_RESOURCE_TYPE_DETAILS_REQUEST";
export const FETCH_RESOURCE_TYPE_DETAILS_SUCCESS = "FETCH_RESOURCE_TYPE_DETAILS_SUCCESS";
export const FETCH_RESOURCE_TYPE_DETAILS_FAILURE = "FETCH_RESOURCE_TYPE_DETAILS_FAILURE";