


export const QUERY_ORGUNIT_FILTER_KEY = "organization";
export const QUERY_ORGUNIT_FILTER_ID = "185";

export const FETCH_APP_CONFIG_REQUEST = "FETCH_APP_CONFIG_REQUEST";
export const FETCH_APP_CONFIG_SUCCESS = "FETCH_APP_CONFIG_SUCCESS";
export const FETCH_APP_CONFIG_FAILURE = "FETCH_APP_CONFIG_FAILURE";


export const FETCH_RESOURCE_TYPE_REQUEST = "FETCH_RESOURCE_TYPE_REQUEST";
export const FETCH_RESOURCE_TYPE_SUCCESS = "FETCH_RESOURCE_TYPE_SUCCESS";
export const FETCH_RESOURCE_TYPE_FAILURE = "FETCH_RESOURCE_TYPE_FAILURE";


export const FETCH_RESOURCE_TYPE_DETAILS_REQUEST = "FETCH_RESOURCE_TYPE_DETAILS_REQUEST";
export const FETCH_RESOURCE_TYPE_DETAILS_SUCCESS = "FETCH_RESOURCE_TYPE_DETAILS_SUCCESS";
export const FETCH_RESOURCE_TYPE_DETAILS_FAILURE = "FETCH_RESOURCE_TYPE_DETAILS_FAILURE";