

export const FETCH_RESOURCE_TYPE_REQUEST = "FETCH_RESOURCE_TYPE_REQUEST";
export const FETCH_RESOURCE_TYPE_SUCCESS = "FETCH_RESOURCE_TYPE_SUCCESS";
export const FETCH_RESOURCE_TYPE_FAILURE = "FETCH_RESOURCE_TYPE_FAILURE";


export const FETCH_RESOURCE_TYPE_DETAILS_REQUEST = "FETCH_RESOURCE_TYPE_DETAILS_REQUEST";
export const FETCH_RESOURCE_TYPE_DETAILS_SUCCESS = "FETCH_RESOURCE_TYPE_DETAILS_SUCCESS";
export const FETCH_RESOURCE_TYPE_DETAILS_FAILURE = "FETCH_RESOURCE_TYPE_DETAILS_FAILURE";


export const REMOVE_SELECTED_RESOURCE_TYPE = "REMOVE_SELECTED_RESOURCE_TYPE";